#google_analytics:

theme: jekyll-theme-minimal

title: JCC Serviços Informacionais
email: contato@joseccandido.com.br

whatsapp: +55 85 9 0000-0000
whatsapp-link: 5585900000000

description: JCC Serviços Informacionais